version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: all
  disable:
    - bodyclose
    - depguard
    - embeddedstructfieldcheck
    - exhaustruct # deprecated
    - exhaustruct_v5
    - funcorder
    - gochecknoglobals
    - goconst
    - gocritic
    - godoclint
    - godox
    - gomodguard # deprecated
    - gosec
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - noinlineerr
    - paralleltest
    - revive
    - tagliatelle
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
    - wsl # deprecated
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 20
    funlen:
      lines: 300
      statements: 150
    maintidx:
      under: 15
  exclusions:
    paths:
      - tmp
    rules:
      - path: _test\.go
        linters:
          - funlen

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
