version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: all
  disable:
    - bodyclose
    - contextcheck
    - cyclop
    - depguard
    - embeddedstructfieldcheck
    - exhaustruct # deprecated
    - exhaustruct_v5
    - funlen
    - funcorder
    - gochecknoglobals
    - goconst
    - gocritic
    - godoclint
    - godox
    - gomodguard # deprecated
    - gosec
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - mnd
    - nilnil
    - noctx
    - noinlineerr
    - paralleltest
    - perfsprint
    - revive
    - tagliatelle
    - testpackage
    - thelper
    - unparam
    - varnamelen
    - wrapcheck
    - wsl # deprecated
    - wsl_v5
  exclusions:
    paths:
      - tmp
    rules:
      - path: _test\.go
        linters:
          - funlen

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
